---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v4.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app mousetrap
  namespace: default
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  interval: 1h
  values:
    defaultPodOptions:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        runAsUser: 0

    controllers:
      mousetrap:
        containers:
          app:
            image:
              repository: docker.io/sirjmann92/mousetrap
              tag: 2.3.20@sha256:e4bb0d9c8a1e5eb74a1f35f243bd6272f65ec2938e870e5bcda31b6d9e1b7dfe
            env:
              TZ: America/New_York
              LOGLEVEL: INFO
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 512Mi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities: {drop: ["ALL"], add: ["SETUID", "SETGID", "CHOWN"]}
              readOnlyRootFilesystem: false

    persistence:
      config:
        existingClaim: mousetrap-config
        globalMounts:
          - path: /config
      logs:
        type: emptyDir
        globalMounts:
          - path: /app/logs
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp

    route:
      main:
        enabled: true
        annotations:
          external-dns.alpha.kubernetes.io/internal: "true"
          external-dns.alpha.kubernetes.io/target: "10.0.6.151"
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        hostnames:
          - mousetrap.eviljungle.com
        rules:
          - matches:
              - path:
                  type: PathPrefix
                  value: /
            backendRefs:
              - name: *app
                port: 39842

    service:
      app:
        controller: mousetrap
        ports:
          http:
            port: 39842
