---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: emqx-core
  namespace: default
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      apps.emqx.io/db-role: core
      apps.emqx.io/instance: emqx
      apps.emqx.io/managed-by: emqx-operator
