{
 "title": "Frigate",
 "tags": [
  "frigate",
  "coral"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "Queue",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "queue" }
   ],
   "targets": [
    {
     "alias": "coral detection queue",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "queue",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "frigate_coral_detection_queue" }
     ]
    },
    {
     "alias": "tracked objects queue",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "queue",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "frigate_tracked_objects_queue" }
     ]
    }
   ]
  },
  {
   "title": "Coral Inference Speed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "speed (ms)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "ms",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "frigate_coral_inference" }
     ]
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "{app_kubernetes_io_name=\"frigate\"}"
    }
   ]
  },
  {
   "title": "coral",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "fps" }
   ],
   "targets": [
    {
     "alias": "fps",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "entity_id" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "FPS",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "frigate_coral_fps" }
     ]
    }
   ]
  },
  {
   "title": "basement",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "fps" }
   ],
   "targets": [
    {
     "alias": "detection fps",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "entity_id" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "FPS",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "basement_detection_fps" }
     ]
    },
    {
     "alias": "fps",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "entity_id" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "FPS",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "basement_fps" }
     ]
    },
    {
     "alias": "skipped fps",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "entity_id" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "FPS",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "basement_skipped_fps" }
     ]
    }
   ]
  },
  {
   "title": "driveway",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short", "label": "fps" }
   ],
   "targets": [
    {
     "alias": "detection fps",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "entity_id" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "FPS",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "driveway_detection_fps" }
     ]
    },
    {
     "alias": "fps",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "entity_id" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "FPS",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "driveway_fps" }
     ]
    },
    {
     "alias": "skipped fps",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "entity_id" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "FPS",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "driveway_skipped_fps" }
     ]
    }
   ]
  },
  {
   "title": "front",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short", "label": "fps" }
   ],
   "targets": [
    {
     "alias": "detection fps",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "entity_id" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "FPS",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "front_detection_fps" }
     ]
    },
    {
     "alias": "fps",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "entity_id" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "FPS",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "front_fps" }
     ]
    },
    {
     "alias": "skipped fps",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "entity_id" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "FPS",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "front_skipped_fps" }
     ]
    }
   ]
  },
  {
   "title": "pool",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short", "label": "fps" }
   ],
   "targets": [
    {
     "alias": "detection fps",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "entity_id" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "FPS",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "pool_detection_fps" }
     ]
    },
    {
     "alias": "fps",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "entity_id" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "FPS",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "pool_fps" }
     ]
    },
    {
     "alias": "skipped fps",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "entity_id" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "FPS",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "pool_skipped_fps" }
     ]
    }
   ]
  },
  {
   "title": "porch",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short", "label": "fps" }
   ],
   "targets": [
    {
     "alias": "detection fps",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "entity_id" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "FPS",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "porch_detection_fps" }
     ]
    },
    {
     "alias": "fps",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "entity_id" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "FPS",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "porch_fps" }
     ]
    },
    {
     "alias": "skipped fps",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "entity_id" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "FPS",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "porch_skipped_fps" }
     ]
    }
   ]
  },
  {
   "title": "FPS (all)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short", "label": "fps" }
   ],
   "targets": [
    {
     "alias": "$tag_entity_id",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "entity_id" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "FPS",
     "query": "SELECT mean(\"value\") FROM \"FPS\" WHERE $timeFilter GROUP BY time($__interval), \"entity_id\" fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}