---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kei
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: kei-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        ICLOUD_USERNAME: "{{ .ICLOUD_USERNAME }}"
        ICLOUD_PASSWORD: "{{ .ICLOUD_PASSWORD }}"
        DISCORD_WEBHOOK_URL: "{{ .DISCORD_WEBHOOK_URL }}"
  dataFrom:
    - extract:
        key: icloudpd
