---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate-operator
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: renovate-secret
  data:
    - secretKey: RENOVATE_TOKEN
      remoteRef:
        key: forgejo - renovate
        property: RENOVATE_TOKEN
    - secretKey: RENOVATE_GITHUB_COM_TOKEN
      remoteRef:
        key: forgejo - renovate
        property: GH_COM_TOKEN
