apiVersion: v1alpha1
kind: CRICustomizationConfig
name: spegel
content: |
  [plugins."io.containerd.cri.v1.images"]
    discard_unpacked_layers = false
  [plugins."io.containerd.cri.v1.runtime"]
    device_ownership_from_security_context = true
---
apiVersion: v1alpha1
kind: EtcFileConfig
name: nfsmount.conf
mode: 0o644
contents: |-
  [ NFSMount_Global_Options ]
  nfsvers=4.2
  hard=True
  nconnect=16
  noatime=True
