---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v4.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: zwave2mqtt
  namespace: default
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  interval: 1h
  values:
    defaultPodOptions:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: aeotec.feature.node.kubernetes.io/zwave
                    operator: In
                    values:
                      - "true"

    controllers:
      zwave:
        containers:
          app:
            image:
              repository: ghcr.io/zwave-js/zwave-js-ui
              tag: 11.16.2@sha256:c43f88e2e395bb4b37c9e87e64998b751b1e1908318177623cebe08867e1eb42
            env:
              TZ: America/New_York
              PORT: &port 8091
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            resources:
              requests:
                cpu: 10m
                memory: 200Mi
              limits:
                memory: 512Mi
                generic-device-plugin/zwave: 1

    persistence:
      config:
        existingClaim: zwave2mqtt-config
        globalMounts:
          - path: /usr/src/app/store
      tmp:
        type: emptyDir

    route:
      main:
        enabled: true
        annotations:
          external-dns.alpha.kubernetes.io/internal: "true"
          external-dns.alpha.kubernetes.io/target: "10.0.6.151"
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        hostnames:
          - z.eviljungle.com
        rules:
          - matches:
              - path:
                  type: PathPrefix
                  value: /
            backendRefs:
              - name: zwave2mqtt
                port: 8091

    service:
      app:
        controller: zwave
        ports:
          http:
            port: *port
          websocket:
            port: 3000
