{
 "title": "cable modem stats",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "30m",
 "panels": [
  {
   "title": "Downstream Power",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "dBm" }
   ],
   "targets": [
    {
     "alias": "ch$tag_channel",
     "groupBy": [
      { "params": [ "channel" ], "type": "tag" }
     ],
     "measurement": "downstream_statistics",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       { "params": [ "power" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Downstream SNR",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "dB" }
   ],
   "targets": [
    {
     "alias": "ch$tag_channel",
     "groupBy": [
      { "params": [ "channel" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "downstream_statistics",
     "select": [
      [
       { "params": [ "snr" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Corrected / Uncorrectables",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "ch$tag_channel",
     "groupBy": [
      { "params": [ "channel" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "downstream_statistics",
     "select": [
      [
       { "params": [ "uncorrectables" ], "type": "field" }
      ],
      [
       { "params": [ "corrected" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Upstream Power",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "dBm" }
   ],
   "targets": [
    {
     "alias": "ch$tag_channel",
     "groupBy": [
      { "params": [ "channel" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "upstream_statistics",
     "select": [
      [
       { "params": [ "power" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Comcast Outages",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "measurement": "logs",
     "query": "SELECT reason_detail AS \"Event\" FROM \"logs\" WHERE (\"friendlyname\" = 'edgerouter ping') AND $timeFilter ",
     "select": [
      [
       { "params": [ "reason_detail" ], "type": "field" },
       { "params": [ "blah" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "friendlyname", "operator": "=", "value": "edgerouter ping" }
     ]
    }
   ]
  }
 ]
}