---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v4.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app minecraft-creative
  namespace: default
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  interval: 1h
  values:
    defaultPodOptions:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000

    controllers:
      minecraft-creative:
        replicas: 0
        strategy: Recreate
        containers:
          app:
            image:
              repository: ghcr.io/itzg/minecraft-server
              tag: 2026.5.4@sha256:f364bae78a0027aee72b01b9b532b1ae0990b3ee8cadbb6a3bc25db77418a25f
            env:
              ENABLE_AUTOPAUSE: "FALSE"
              EULA: "true"
              TYPE: PAPER
              VERSION: LATEST
              DIFFICULTY: normal
              MODE: creative
              ONLINE_MODE: "false"
              FORCE_REDOWNLOAD: "TRUE"
              MEMORY: 5120M
              MAX_WORLD_SIZE: "5999968"
              MAX_TICK_TIME: "-1"
              LEVEL: world-20160823
              ICON: https://www.freeiconspng.com/uploads/minecraft-server-icon-13.png
              MOTD: "§feviljungle§ - §a§lcreative§"
              JVM_OPTS: "-Xms5G -Xmx5G -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true"
              MODS: "https://cdn.modrinth.com/data/hXiIvTyT/versions/puUfqBpY/EssentialsX-2.20.1.jar,https://cdn.modrinth.com/data/Lu3KuzdV/versions/llmrc4cl/CoreProtect-22.4.jar"
              SPIGET_RESOURCES: "83557,4441"
              MODRINTH_PROJECTS: "nochatreports-spigot-paper"
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  exec:
                    command: ["mc-monitor", "status", "--host", "127.0.0.1", "--port", "25565"]
                  initialDelaySeconds: 30
                  periodSeconds: 5
                  failureThreshold: 10
                  successThreshold: 1
                  timeoutSeconds: 1
              readiness:
                enabled: true
                custom: true
                spec:
                  exec:
                    command: ["mc-monitor", "status", "--host", "127.0.0.1", "--port", "25565"]
                  initialDelaySeconds: 30
                  periodSeconds: 5
                  failureThreshold: 10
                  successThreshold: 1
                  timeoutSeconds: 1
              startup:
                enabled: true
                custom: true
                spec:
                  exec:
                    command: ["mc-monitor", "status", "--host", "127.0.0.1", "--port", "25565"]
                  failureThreshold: 30
                  periodSeconds: 10
            resources:
              requests:
                memory: 6Gi
                cpu: 250m
              limits:
                memory: 7Gi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities: {drop: ["ALL"]}

    persistence:
      data:
        existingClaim: minecraft-creative-datadir
        globalMounts:
          - path: /data

    service:
      app:
        controller: minecraft-creative
        ports:
          minecraft:
            port: 25565
            protocol: TCP
