---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app minecraft-rcon-web
  namespace: default
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  interval: 1h
  values:
    defaultPodOptions:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000

    controllers:
      minecraft-rcon-web:
        containers:
          app:
            image:
              repository: itzg/rcon
              tag: latest@sha256:c9521f333bf9eaedf2db0acd750e67be88eaaa9c5e9026385bd875dc18a49110
            resources:
              requests:
                cpu: 10m
                memory: 64Mi
              limits:
                memory: 128Mi
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  tcpSocket:
                    port: 4326
                  initialDelaySeconds: 15
                  periodSeconds: 30
                  failureThreshold: 3
              readiness:
                enabled: true
                custom: true
                spec:
                  tcpSocket:
                    port: 4326
                  initialDelaySeconds: 15
                  periodSeconds: 15
                  failureThreshold: 3
            env:
              RWA_USERNAME: admin
              RWA_ADMIN: "TRUE"
              RWA_RCON_HOST: minecraft-survival
              RWA_RCON_PORT: "25575"
              RWA_GAME: minecraft
              RWA_WEBSOCKET_URL_SSL: "wss://mcrcon.eviljungle.com/ws"
            envFrom:
              - secretRef:
                  name: minecraft-rcon-web-secret
            securityContext:
              allowPrivilegeEscalation: false
              capabilities: {drop: ["ALL"]}
              readOnlyRootFilesystem: false

    persistence:
      db:
        existingClaim: minecraft-rcon-web-db
        globalMounts:
          - path: /opt/rcon-web-admin/db

    route:
      app:
        annotations:
          external-dns.alpha.kubernetes.io/internal: "true"
          external-dns.alpha.kubernetes.io/target: "10.0.6.151"
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        hostnames:
          - mcrcon.eviljungle.com
        rules:
          - matches:
              - path: {type: PathPrefix, value: /ws}
            backendRefs:
              - name: minecraft-rcon-web
                port: 4327
          - matches:
              - path: {type: PathPrefix, value: /}
            backendRefs:
              - name: minecraft-rcon-web
                port: 4326

    service:
      app:
        controller: minecraft-rcon-web
        ports:
          http:
            port: 4326
          websocket:
            port: 4327
