---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app minecraft-survival
  namespace: default
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  interval: 1h
  values:
    defaultPodOptions:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000

    controllers:
      minecraft-survival:
        replicas: 1
        strategy: Recreate
        containers:
          app:
            image:
              repository: ghcr.io/itzg/minecraft-server
              tag: 2026.5.4@sha256:f364bae78a0027aee72b01b9b532b1ae0990b3ee8cadbb6a3bc25db77418a25f
            env:
              ENABLE_AUTOPAUSE: "FALSE"
              EULA: "true"
              TYPE: PAPER
              VERSION: LATEST
              DIFFICULTY: normal
              MODE: survival
              PVP: "false"
              ONLINE_MODE: "false"
              OVERRIDE_SERVER_PROPERTIES: "true"
              FORCE_REDOWNLOAD: "TRUE"
              MEMORY: 7168M
              MAX_WORLD_SIZE: "5999968"
              MAX_TICK_TIME: "-1"
              SPAWN_PROTECTION: "0"
              LEVEL: "1.21-20240629-5"
              SEED: "1.21-20240629-5"
              OPS: billimek
              ICON: https://www.freeiconspng.com/uploads/minecraft-server-icon-23.png
              MOTD: "mcsv.eviljungle.com\n§6§lSMPl§r§l - §r§c§lSMP§r\n"
              JVM_OPTS: "-Xms7168M -Xmx7168M --add-modules=jdk.incubator.vector -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20"
              MODS: "https://cdn.modrinth.com/data/hXiIvTyT/versions/nY6VN1XH/EssentialsX-2.22.0.jar,https://cdn.modrinth.com/data/Lu3KuzdV/versions/6W2ad1iI/CoreProtect-CE-23.2.jar,https://cdn.modrinth.com/data/18HN6DXd/versions/HIMl6isS/LockedChestsPlugin-1.0.jar,https://cdn.modrinth.com/data/Vebnzrzj/versions/cfNN7sys/LuckPerms-Bukkit-5.4.145.jar,https://cdn.modrinth.com/data/7KTcTCzs/versions/bMcXRaEu/FreezeHibernate-1.0.jar,https://cdn.modrinth.com/data/UmLGoGij/versions/MK210KrY/DiscordSRV-Build-1.29.0.jar"
              MODRINTH_PROJECTS: "bluemap,nochatreports-spigot-paper"
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  exec:
                    command: ["mc-monitor", "status", "--host", "127.0.0.1", "--port", "25565"]
                  initialDelaySeconds: 30
                  periodSeconds: 5
                  failureThreshold: 10
              readiness:
                enabled: true
                custom: true
                spec:
                  exec:
                    command: ["mc-monitor", "status", "--host", "127.0.0.1", "--port", "25565"]
                  initialDelaySeconds: 30
                  periodSeconds: 5
                  failureThreshold: 10
              startup:
                enabled: true
                custom: true
                spec:
                  exec:
                    command: ["mc-monitor", "status", "--host", "127.0.0.1", "--port", "25565"]
                  failureThreshold: 30
                  periodSeconds: 10
            resources:
              requests:
                memory: 9Gi
                cpu: 500m
              limits:
                memory: 9Gi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities: {drop: ["ALL"]}

    persistence:
      data:
        existingClaim: minecraft-survival-datadir
        globalMounts:
          - path: /data

    route:
      bluemap:
        annotations:
          external-dns.alpha.kubernetes.io/internal: "true"
          external-dns.alpha.kubernetes.io/target: "10.0.6.151"
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        hostnames:
          - mcsv-map.eviljungle.com
        rules:
          - matches:
              - path: {type: PathPrefix, value: /}
            backendRefs:
              - name: minecraft-survival
                port: 8100

    service:
      app:
        controller: minecraft-survival
        ports:
          minecraft:
            port: 25565
            protocol: TCP
          bluemap:
            port: 8100
