---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v4.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: seerr
  namespace: default
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  interval: 1h
  values:
    defaultPodOptions:
      securityContext:
        fsGroup: 1001
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 1001
        runAsNonRoot: true
        runAsUser: 1001
        seccompProfile: { type: RuntimeDefault }

    controllers:
      seerr:
        containers:
          app:
            image:
              repository: ghcr.io/seerr-team/seerr
              tag: v3.2.0@sha256:c4cbd5121236ac2f70a843a0b920b68a27976be57917555f1c45b08a1e6b2aad
            env:
              TZ: America/New_York
              LOG_LEVEL: "info"
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/v1/status
                    port: 5055
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            resources:
              requests:
                cpu: 10m
                memory: 250Mi
              limits:
                memory: 1Gi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities: { drop: ["ALL"] }
              readOnlyRootFilesystem: true

    persistence:
      config:
        existingClaim: seerr-config
        type: persistentVolumeClaim
        globalMounts:
          - path: /app/config
      tmpfs:
        type: emptyDir
        advancedMounts:
          seerr:
            app:
              - path: /app/config/logs
                subPath: logs
              - path: /tmp
                subPath: tmp

    route:
      app:
        annotations:
          external-dns.alpha.kubernetes.io/external: "true"
        parentRefs:
          - name: public
            namespace: kube-system
            sectionName: https
        hostnames:
          - &host request.eviljungle.com
      internal:
        annotations:
          external-dns.alpha.kubernetes.io/internal: "true"
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        hostnames:
          - *host

    service:
      app:
        controller: seerr
        ports:
          http:
            port: 5055
