{
 "title": "Home Assistant",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Light Level",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "lumens" }
   ],
   "targets": [
    {
     "expr": "hass_sensor_unit_percent{entity=\"sensor.wyze_1_light_sensor\"}/1000",
     "legendFormat": "wyze-1"
    },
    {
     "expr": "hass_sensor_unit_percent{entity=\"sensor.wyze_2_light_sensor\"}/1000",
     "legendFormat": "wyze-2"
    },
    {
     "expr": "hass_sensor_unit_percent{entity=\"sensor.wyze_3_light_sensor\"}/1000",
     "legendFormat": "wyze-3"
    }
   ]
  },
  {
   "title": "☠️US Coronavirus infections ☣️",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "🤷‍♂️" }
   ],
   "targets": [
    {
     "alias": "🤷‍♂️",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "people",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "us_coronavirus_confirmed" }
     ]
    }
   ]
  },
  {
   "title": "Tesla Battery & Range",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "% charge",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "%",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "sulaco_battery_sensor" }
     ]
    },
    {
     "alias": "range (miles)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "mi",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "sulaco_range_sensor" }
     ]
    }
   ]
  },
  {
   "title": "Temperature & Humidity",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "farenheit" }
   ],
   "targets": [
    {
     "alias": "Downstairs Observed Temperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "°F",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "domain", "operator": "=", "value": "sensor" },
      {
       "condition": "AND",
       "key": "entity_id",
       "operator": "=",
       "value": "downstairs_thermostat_temperature"
      }
     ]
    },
    {
     "alias": "Downstairs Target Temperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "°F",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "domain", "operator": "=", "value": "sensor" },
      { "condition": "AND", "key": "entity_id", "operator": "=", "value": "downstairs_thermostat_target" }
     ]
    },
    {
     "alias": "Outside Temperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "°F",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "domain", "operator": "=", "value": "sensor" },
      { "condition": "AND", "key": "entity_id", "operator": "=", "value": "weather_temperature" }
     ]
    },
    {
     "alias": "Downstairs Inside Humidity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "%",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "domain", "operator": "=", "value": "sensor" },
      { "condition": "AND", "key": "entity_id", "operator": "=", "value": "downstairs_thermostat_humidity" }
     ]
    },
    {
     "alias": "Outside Humidity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "%",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "domain", "operator": "=", "value": "sensor" },
      { "condition": "AND", "key": "entity_id", "operator": "=", "value": "weather_humidity" }
     ]
    }
   ]
  },
  {
   "title": "HVAC State",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "alias": "Downstairs HVAC State",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sensor.downstairs_thermostat_hvac_state",
     "select": [
      [
       { "params": [ "state" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    },
    {
     "alias": "Downstairs Temperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "°F",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "domain", "operator": "=", "value": "sensor" },
      {
       "condition": "AND",
       "key": "entity_id",
       "operator": "=",
       "value": "downstairs_thermostat_temperature"
      }
     ]
    },
    {
     "alias": "Upstairs HVAC State",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sensor.master_bedroom_thermostat_nest_hvac_state",
     "select": [
      [
       { "params": [ "state" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    },
    {
     "alias": "Upstairs Temperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "°F",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "domain", "operator": "=", "value": "sensor" },
      {
       "condition": "AND",
       "key": "entity_id",
       "operator": "=",
       "value": "master_bedroom_thermostat_nest_temperature"
      }
     ]
    },
    {
     "alias": "Outside Temperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "°F",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "weather_temperature" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "downstairs",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Wind Speed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "velocitymph" }
   ],
   "targets": [
    {
     "alias": "$tag_entity_id",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "entity_id" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "mph",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Jeff's iPhone Battery State",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "sensor.battery_state",
     "select": [
      [
       { "params": [ "Battery Level" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Jen's iPhone Battery State",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "sensor.battery_state_2",
     "select": [
      [
       { "params": [ "Battery Level" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Jeff's Phone Bluetooth RSSI",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "dBm" }
   ],
   "targets": [
    {
     "alias": "$tag_entity_id",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "entity_id" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "dBm",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "jeff_basement_rssi" },
      { "condition": "OR", "key": "entity_id", "operator": "=", "value": "jeff_dining_rssi" },
      { "condition": "OR", "key": "entity_id", "operator": "=", "value": "jeff_garage_rssi" },
      { "condition": "OR", "key": "entity_id", "operator": "=", "value": "jeff_livingroom_rssi" }
     ]
    }
   ]
  },
  {
   "title": "Jen's Phone Bluetooth RSSI",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "yaxes": [
    { "format": "dBm" }
   ],
   "targets": [
    {
     "alias": "$tag_entity_id",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "entity_id" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "dBm",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "jen_basement_rssi" },
      { "condition": "OR", "key": "entity_id", "operator": "=", "value": "jen_dining_rssi" },
      { "condition": "OR", "key": "entity_id", "operator": "=", "value": "jen_garage_rssi" },
      { "condition": "OR", "key": "entity_id", "operator": "=", "value": "jen_livingroom_rssi" }
     ]
    }
   ]
  }
 ]
}