---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v4.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: unifi-poller
  namespace: monitoring
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  interval: 1h
  values:
    defaultPodOptions:
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault

    controllers:
      unifi-poller:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/unpoller/unpoller
              tag: v3.1.0@sha256:ff571f97218ad3d47f4428e7283120597fffc63a7f903fddde6d7a02a6d95769
            env:
              TZ: America/New_York
              UP_INFLUXDB_DISABLE: "true"
              UP_PROMETHEUS_HTTP_LISTEN: 0.0.0.0:9130
              UP_UNIFI_DEFAULT_ROLE: view-only
              UP_UNIFI_DEFAULT_URL: https://unifi.default.svc.cluster.local:8443
              UP_UNIFI_DEFAULT_VERIFY_SSL: "false"
              UP_UNIFI_DEFAULT_SAVE_SITES: "true"
              UP_UNIFI_DEFAULT_SAVE_DPI: "false"
            envFrom:
              - secretRef:
                  name: unifi-poller-secret
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: 9130
                  initialDelaySeconds: 15
                  periodSeconds: 30
                  timeoutSeconds: 3
                  failureThreshold: 3
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: 9130
                  initialDelaySeconds: 10
                  periodSeconds: 30
                  timeoutSeconds: 3
            resources:
              requests:
                cpu: 10m
                memory: 64Mi
              limits:
                memory: 128Mi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop: ["ALL"]
              readOnlyRootFilesystem: true

    service:
      app:
        controller: unifi-poller
        ports:
          http:
            port: 9130
