---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/tuppr.home-operations.com/talosupgrade_v1alpha1.json
apiVersion: tuppr.home-operations.com/v1alpha1
kind: TalosUpgrade
metadata:
  name: talos
  namespace: system-upgrade
spec:
  talos:
    # renovate: datasource=github-releases depName=siderolabs/talos
    version: v1.14.0
  policy:
    rebootMode: default
  healthChecks:
    - apiVersion: kopiur.home-operations.com/v1alpha1
      kind: Snapshot
      expr: |-
        status.phase != 'Pending' && status.phase != 'Running'
    - apiVersion: ceph.rook.io/v1
      kind: CephCluster
      expr: |-
        status.ceph.health in ['HEALTH_OK', 'HEALTH_WARN']
    - apiVersion: postgresql.cnpg.io/v1
      kind: Cluster
      expr: |-
        status.phase in ['Cluster in healthy state']
