---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/kopiur.home-operations.com/clusterrepository_v1alpha1.json
apiVersion: kopiur.home-operations.com/v1alpha1
kind: ClusterRepository
metadata:
  name: nas
spec:
  allowedNamespaces:
    all: true
  backend:
    filesystem:
      path: /repository
      volume:
        nfs:
          server: nas.home
          path: /mnt/ssdtank/kopia/.kopiur
  create:
    enabled: true
  credentialProjection:
    allowed: true
  encryption:
    passwordSecretRef:
      name: kopiur-nas-secret
      namespace: kube-system
      key: KOPIA_PASSWORD
  identityDefaults:
    hostnameExpr: "namespace"
    usernameExpr: "namespace + '-' + policyName"
  moverDefaults:
    podSecurityContext:
      runAsNonRoot: true
      fsGroupChangePolicy: OnRootMismatch
    cache:
      capacity: 1Gi
      storageClassName: ceph-block
      mode: Ephemeral
    ttlSecondsAfterFinished: 300
