---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kopiur-nas
  namespace: kube-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: kopiur-nas-secret
    template:
      engineVersion: v2
      data:
        KOPIA_PASSWORD: "{{ .KOPIA_PASSWORD }}"
  dataFrom:
    - extract:
        key: kopia
