---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kopiur
  namespace: kube-system
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.4.13
    digest: sha256:b0e50a9abbe1db7cead13267c9a0e73e64ef52271cab7d0e869545973e2db751
  url: oci://ghcr.io/home-operations/charts/kopiur
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kopiur
  namespace: kube-system
spec:
  chartRef:
    kind: OCIRepository
    name: kopiur
  interval: 1h
  values:
    installScope: cluster
    installCRDs: true
    controller:
      streamingLists: true
      extraVolumes:
        - name: repository
          nfs:
            server: nas.home
            path: /mnt/ssdtank/kopia/.kopiur
      extraVolumeMounts:
        - name: repository
          mountPath: /repository
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
    features:
      credentialProjection:
        enabled: true
    webhook:
      tls:
        mode: self
      serviceMonitor:
        enabled: true
    metrics:
      serviceMonitor:
        enabled: true
      prometheusRule:
        enabled: true
    grafanaDashboard:
      enabled: true
      grafanaOperator:
        enabled: true
        allowCrossNamespaceImport: true
        matchLabels:
          dashboards: grafana
    podSecurityContext:
      runAsNonRoot: true
      runAsUser: 65534
      runAsGroup: 65534
      fsGroup: 65534
      fsGroupChangePolicy: OnRootMismatch
