---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana
  namespace: monitoring
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: grafana-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        admin-user: "admin"
        admin-password: "{{ .GRAFANA_ADMIN_PASSWORD }}"
        TESLAMATE_DB_PASSWORD: "{{ .TESLAMATE_POSTGRES_PASS }}"
  dataFrom:
    - extract:
        key: grafana
    - extract:
        key: teslamate
