---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/grafana.integreatly.org/grafanaserviceaccount_v1beta1.json
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaServiceAccount
metadata:
  name: mcp-readonly
  namespace: monitoring
spec:
  instanceName: grafana
  name: mcp-readonly
  role: Viewer
  tokens:
    - name: mcp-token
      secretName: grafana-mcp-token
